name: ovbot

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: x86_64 (ubuntu-latest)

    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - uses: actions/setup-python@v2
        with:
          python-version: '2.9'

      - name: Build python 2.9
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8 future
